Repository SOM-st/SOM, pull requests merged in 2021-12, with the labels that each got.

#87 Added TestGC and SomParse benchmarks, and adapt SomSom to not measure host parser
  Examples/Benchmarks/SomParse.som
  Examples/Benchmarks/TestSuite/TestGC.som
  SomSom/src/vm/Main.som
  SomSom/src/vm/MainLoadAll.som
Labels: enhancement

#88 Make SomParse compatible with bytecode limits
  Examples/Benchmarks/SomParse.som
Labels: bug

#86 Added `Integer>>#raisedTo:` and `Double>>#raisedTo:`
  Smalltalk/Double.som
  Smalltalk/Integer.som
  TestSuite/DoubleTest.som
  TestSuite/IntegerTest.som
Labels: enhancement, spec, language design

#93 Fixed `Vector>>#remove` and `Vector>>#removeFirst` to allow deallocations
  Smalltalk/Vector.som
  TestSuite/VectorTest.som
Labels: bug, enhancement
